version: "3"

services:
#  web-app:
#    build:
#      context: ./web-app
#      dockerfile: ./Dockerfile
###    command: flask run --port=3000
#    environment:
#      SQLALCHEMY_DATABASE_URI: postgresql://user:password@pg:5432/app
#    ports:
#      - 5000:5000
#    depends_on:
#      - pg

  pg:
    image: postgres:13
    environment:
      POSTGRES_DB: "tournament"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - 5454:5432