"""empty message

Revision ID: 11c5b73c53e2
Revises: 81a15a040bcb
Create Date: 2022-11-27 15:56:40.577234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c5b73c53e2'
down_revision = '81a15a040bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place_photos', sa.Column('ext', sa.String(length=5), nullable=False))
    op.drop_column('place_photos', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place_photos', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('place_photos', 'ext')
    # ### end Alembic commands ###
