"""add state to tournaments

Revision ID: 7e7b28b54f9e
Revises: c2076a576ec7
Create Date: 2022-10-05 10:26:12.365909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7b28b54f9e'
down_revision = 'c2076a576ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('state', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'state')
    # ### end Alembic commands ###
