"""empty message

Revision ID: 8222b401634c
Revises: 11c5b73c53e2
Create Date: 2022-11-27 16:35:31.869108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8222b401634c'
down_revision = '11c5b73c53e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place_photos', sa.Column('width', sa.Integer(), nullable=False))
    op.add_column('place_photos', sa.Column('height', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place_photos', 'height')
    op.drop_column('place_photos', 'width')
    # ### end Alembic commands ###
