"""empty message

Revision ID: c2076a576ec7
Revises: d47acf559937
Create Date: 2022-08-21 09:50:52.193223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2076a576ec7'
down_revision = 'd47acf559937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attempts_comp_id_fkey', 'attempts', type_='foreignkey')
    op.create_foreign_key(None, 'attempts', 'competitions', ['comp_id'], ['id'])
    op.drop_constraint('commands_comp_id_fkey', 'commands', type_='foreignkey')
    op.create_foreign_key(None, 'commands', 'tournaments', ['comp_id'], ['id'])
    op.drop_constraint('competitions_tour_id_fkey', 'competitions', type_='foreignkey')
    op.drop_constraint('competitions_speciality_id_fkey', 'competitions', type_='foreignkey')
    op.drop_constraint('competitions_category_id_fkey', 'competitions', type_='foreignkey')
    op.create_foreign_key(None, 'competitions', 'tournaments', ['tour_id'], ['id'])
    op.create_foreign_key(None, 'competitions', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'competitions', 'speciality', ['speciality_id'], ['id'])
    op.drop_constraint('gates_comp_id_fkey', 'gates', type_='foreignkey')
    op.create_foreign_key(None, 'gates', 'competitions', ['comp_id'], ['id'])
    op.drop_constraint('start_protocols_card_id_fkey', 'start_protocols', type_='foreignkey')
    op.create_foreign_key(None, 'start_protocols', 'cards', ['card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'start_protocols', type_='foreignkey')
    op.create_foreign_key('start_protocols_card_id_fkey', 'start_protocols', 'sportsmen', ['card_id'], ['id'])
    op.drop_constraint(None, 'gates', type_='foreignkey')
    op.create_foreign_key('gates_comp_id_fkey', 'gates', 'sport_types', ['comp_id'], ['id'])
    op.drop_constraint(None, 'competitions', type_='foreignkey')
    op.drop_constraint(None, 'competitions', type_='foreignkey')
    op.drop_constraint(None, 'competitions', type_='foreignkey')
    op.create_foreign_key('competitions_category_id_fkey', 'competitions', 'sport_types', ['category_id'], ['id'])
    op.create_foreign_key('competitions_speciality_id_fkey', 'competitions', 'sport_types', ['speciality_id'], ['id'])
    op.create_foreign_key('competitions_tour_id_fkey', 'competitions', 'sport_types', ['tour_id'], ['id'])
    op.drop_constraint(None, 'commands', type_='foreignkey')
    op.create_foreign_key('commands_comp_id_fkey', 'commands', 'competitions', ['comp_id'], ['id'])
    op.drop_constraint(None, 'attempts', type_='foreignkey')
    op.create_foreign_key('attempts_comp_id_fkey', 'attempts', 'sport_types', ['comp_id'], ['id'])
    # ### end Alembic commands ###
