"""empty message

Revision ID: d47acf559937
Revises: f1f37b47d893
Create Date: 2022-08-20 20:33:50.073029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47acf559937'
down_revision = 'f1f37b47d893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('hard_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('patronymic', sa.String(length=30), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sport_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('comp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comp_id'], ['sport_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comp', sa.String(length=100), nullable=False),
    sa.Column('begin', sa.Date(), nullable=False),
    sa.Column('start_gate', sa.Integer(), nullable=False),
    sa.Column('finish_gate', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=True),
    sa.Column('speciality_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['sport_types.id'], ),
    sa.ForeignKeyConstraint(['speciality_id'], ['sport_types.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['sport_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comp')
    )
    op.create_table('gates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('hard_id', sa.Integer(), nullable=False),
    sa.Column('comp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comp_id'], ['sport_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pers_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['pers_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pers_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pers_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speciality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec', sa.String(length=100), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['sport_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spec')
    )
    op.create_table('sportsmen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pers_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pers_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempt_referees',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('refer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['refer_id'], ['referees.id'], ),
    sa.PrimaryKeyConstraint('attempt_id', 'refer_id')
    )
    op.create_table('commands',
    sa.Column('comp_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comp_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('comp_id', 'team_id')
    )
    op.create_table('refer_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('gate_id', sa.Integer(), nullable=False),
    sa.Column('refer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ),
    sa.ForeignKeyConstraint(['refer_id'], ['referees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('start_protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('sportsman_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['sportsmen.id'], ),
    sa.ForeignKeyConstraint(['sportsman_id'], ['sportsmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tour_referees',
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('refer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['refer_id'], ['referees.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('tour_id', 'refer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tour_referees')
    op.drop_table('start_protocols')
    op.drop_table('refer_notes')
    op.drop_table('commands')
    op.drop_table('attempt_referees')
    op.drop_table('sportsmen')
    op.drop_table('speciality')
    op.drop_table('referees')
    op.drop_table('persons_data')
    op.drop_table('gates')
    op.drop_table('competitions')
    op.drop_table('attempts')
    op.drop_table('teams')
    op.drop_table('sport_types')
    op.drop_table('persons')
    op.drop_table('category')
    op.drop_table('cards')
    # ### end Alembic commands ###
